#!/usr/bin/perl -w

=head1 NAME

clean-TAGS - fix TAGS file generated by cperl-mode

=head1 SYNOPSIS

filter duplicate definitions

=head1 DESCRIPTION

(cd "~/projects/mailnesia.com/")
(cperl-write-tags nil t t t)
perl clean-TAGS.pl [filename]

=cut

use strict;

my $filename;

unless ( $filename = $ARGV[0] )
{
    die "filename?\n"
}

unless (-e $filename && -s $filename)
{
    die "error opening TAGS file $filename (does not exist or 0 length)\n";
}

open TAGS, "<", $filename || die "unable to open TAGS for reading\n";

my %position;
my $tags_done;
my $tags_original;


LINE: while ( <TAGS> )
{
    $tags_original .= $_;
    undef %position if m/^$/; # track positions per file

    if ( m/(\d+,\d+)$/ )
    {
        my $current_position = $1;

        if ( exists $position{$current_position} )
        {
            next LINE;          # filter duplicate positions
        }
        else
        {
            $position{$current_position} = 1;
        }
    }

    $tags_done .= $_;

}

if ($tags_done ne $tags_original)
{            # only write out new file if it's different from original
    open TAGS, ">", $filename || die "unable to open TAGS for writing\n";
    print TAGS $tags_done;
}


close TAGS;
